### ISSUE TITLE
What is the difference between this theme and the jetBrains plugin?

### ISSUE THREAD

**Issue by ReactGirl** [AradiPatrik/one-dark-native-intellij#1]
What is the difference between this theme from the 
jetBrains **Atom OneDark Theme** ?

https://plugins.jetbrains.com/plugin/index?xmlId=github.cweijan.test-theme

**Comment by AradiPatrik** [comment]
At the time I did this, native theming only came out, so I experimented by copying the atom's one dark. I don't know if cweijans plugin is developed using native theming. If it is then, I'm sure that his or her is better, for this repo is only an experiment by me, and need some tweaking to look smooth. (indent guides are bright white so you need to hide them manually, and that you have to set them to translucent in the editor settings).
Also I don't know if his is open source, but this is, so if you are interested in the intellij's native theming maybe you can help smooth out some edges, which I wasn't able to do :)

**Comment by ReactGirl** [comment]
Hi Aradi. Thanks for the information. I like the colors of your theme better.
Just a question, what does native theming mean?

**Comment by AradiPatrik** [comment]
Well in the past Intellij didn't support customizing the ui colors, it only allowed customization of the editor colors (through settings). So if you wanted intellij to look completely different, as a theme developer you had a hacky way ahead of you. Since  March 14, 2019 they made it, so you didn't have to use workarounds and hacks to customize the ui, developing the ui skin now is just a simple as writing a JSON file.
So native means that the editor is prepared for customization :)
This blog post sums it up pretty nicely: https://blog.jetbrains.com/idea/2019/03/brighten-up-your-day-add-color-to-intellij-idea/. 
And if you are interested in how to create a theme plugin yourself, take a look at this: http://www.jetbrains.org/intellij/sdk/docs/reference_guide/ui_themes/themes_intro.html.
